Caught exception! <%= @exception.message %>

<%= @exception.backtrace.join("\n") %>
